services:
  mysql:
    image: mysql:8.0
    container_name: morago-mysql
    restart: on-failure
    environment:
      MYSQL_DATABASE: morago
      MYSQL_ROOT_PASSWORD: root
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "33066:3306"

volumes:
  db_data:
