spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: morago-backend
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  flyway:
    enabled: false
    url: ${DATABASE_URL}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    baselineOnMigrate: true
    validateMigrationNaming: true

jwt:
    secret: your-very-secure-secret-key-1234567890
    expiration: 86400000