spring:
  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&serverTimezone=UTC
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}

  flyway:
    enabled: false
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&serverTimezone=UTC
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    baselineOnMigrate: true
    validateMigrationNaming: true
