spring:
#  TODO после Security
#  app:
#    jwtSecret: ${JWT_SECRET}
#    jwtExpirationMs: ${JWT_EXPIRATION}
#    refreshTokenExpirationMs: ${REFRESH_TOKEN_EXPIRATION}
  config:
    import: optional:file:.env[.properties]
  application:
    name: morago-backend
  datasource:
    url: jdbc:mysql://localhost:33060/morago
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    url: jdbc:mysql://localhost:33060/morago
    user: root
    password: root
    baselineOnMigrate: true
    validateMigrationNaming: true